spring:
  data:
    mongodb:
      uri: mongodb+srv://mongodb:P@ssword1234!@mongodb.mongocluster.cosmos.azure.com/catalog?tls=true&authMechanism=SCRAM-SHA-256&retrywrites=false&maxIdleTimeMS=120000
      database: catalog

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

otel:
  exporter:
    otlp:
      endpoint: http://localhost:4318
  service:
    name: catalog-service
  traces:
    exporter: otlp
  metrics:
    exporter: otlp
  logs:
    exporter: otlp
